pognetwork/champ

Cargo.lock
README.md
champ/lib/storage/Cargo.toml
champ/lib/storage/lib.rs
champ/lib/storage/rocksdb/rocksdb.rs
champ/lib/storage/scylla/scylla.rs
champ/node/Cargo.toml
champ/node/main.rs
champ/node/rpc/account.rs
champ/node/state.rs
docs/event-loop.md
docs/index.md
docs/storage-layer.md
docs/techstack.drawio.svg

* Storage Crate now exposes a `DatabaseConfig` struct for configuring the type and connection details
* Added `storage::new` for createing new database instances
* Added `InMemory` database type for a memdb for running tests & debugging
* Added Database to champ state struct
* Different Database Backends can be enabled or disabled with feature flags
* Removed RocksDB from default backends to require less dependencies for compiling

feat: add basic database methods

---

Cargo.lock
champ/node/main.rs
champ/node/rpc/account.rs
champ/node/state.rs

Adds get_balance gRPC method to Account Service

feat(node): Account service balance

---

Cargo.lock
champ/node/rpc/account.rs

Adds getVotingPower fn

---

Cargo.lock
champ/node/Cargo.toml
champ/node/rpc/account.rs

feat(node): Adds getBlockbyID

---

Cargo.lock
champ/lib/storage/lib.rs
champ/lib/storage/mock/mock.rs
champ/lib/storage/rocksdb/rocksdb.rs
champ/lib/storage/scylla/scylla.rs

feat(storage): get_block_by_account_before

---

champ/node/consensus.rs
champ/node/consensus/graphs.rs
champ/node/consensus/voting_power.rs
champ/node/rpc/account.rs

Adds functions to add the delegated power to an account but limits the power by a factor of 30%
- get-max_voting_power is has missing logic
- Untested

Delegate voting

---

Cargo.lock
champ/lib/crypto/Cargo.toml
champ/lib/p2p/Cargo.toml
champ/lib/roughtime/Cargo.toml
champ/lib/roughtime/client.rs
champ/lib/roughtime/lib.rs
champ/lib/roughtime/server.rs
champ/lib/storage/Cargo.toml
champ/node/Cargo.toml
champ/node/http/server.rs
champ/node/main.rs

feat: implement roughtime server

---

Cargo.lock
champ/lib/storage/mock/mock.rs
champ/node/rpc/account.rs

- Addresses now use bytes instead of strings

feat(rpcFunctions): Adds get Delegate function and cleans up

---

.github/workflows/release.yaml
release.toml

fix: fix github release creation

---

.github/workflows/release.yaml
release.toml

fix: fix tagging

---

.github/workflows/release.yaml
CHANGELOG.md
RELEASE_NOTES.md

build: improve release notes

---

champ/lib/storage/lib.rs
champ/lib/storage/mock/mock.rs
champ/lib/storage/scylla/scylla.rs
champ/node/consensus/voting_power.rs
champ/node/validation/block.rs

adds rough logic to validate the previous block
I think its missing logic atm

feat(validation): Validate previous block

---

Cargo.lock
champ/node/auth/permissions.rs
champ/node/config.rs
champ/node/rpc/node_admin.rs
champ/node/rpc/server.rs

feat: implement missing admin gRPC methods

---

champ/node/blockpool/pool.rs
champ/node/validation/block.rs

chore: Improve blockpool error handling (TG-35)

---

champ/node/storage/sled/sled.rs

Signed-off-by: Henry Gressmann <mail@henrygressmann.de>

fix: add by_acc key (TG-42)

---

champ/node/validation/block.rs

perf: concurrent validation (TG-43)

---

champ/node/state.rs
champ/node/validation/block.rs

_maybe_...
kinda suspicious that it works 

test: fixed validation tests

---

Cargo.lock
champ/node/consensus/graphs.rs
champ/node/consensus/snapshots/champ_node__consensus__graphs__tests__snapshots-3.snap
champ/node/consensus/voting_power.rs

feat: improved inactive tax and added some normalization

---

Cargo.lock
champ/node/Cargo.toml
champ/node/metrics.rs
champ/node/rpc/server.rs
champ/node/validation/block.rs

Signed-off-by: Henry Gressmann <mail@henrygressmann.de>

chore: slightly improve metrics

---

Cargo.lock
champ/lib/crypto/password.rs
champ/lib/encoding/Cargo.toml
champ/lib/encoding/adad.rs
champ/lib/encoding/lib.rs
champ/node/Cargo.toml
champ/node/storage/database.rs
champ/node/storage/sql/main.rs

Specification: https://pog.network/specification/PIPs/04-ADAD/
This PR doesn't actually implement ADAD for our datastructures, this will happen in a seperate PR.

feat: Implement PRC-4: Authenticated Data with Associated Data

---

Cargo.lock
champ/node/Cargo.toml
champ/node/auth/interceptors.rs
champ/node/blockpool/pool.rs
champ/node/consensus/graphs.rs
champ/node/consensus/voting_power.rs
champ/node/rpc/block.rs
champ/node/rpc/node_admin.rs
champ/node/rpc/node_wallet_manager.rs
champ/node/storage/database.rs
champ/node/storage/sled/main.rs
champ/node/storage/sql/entity/Cargo.toml
champ/node/storage/sql/entity/entities/block.rs
champ/node/storage/sql/main.rs
champ/node/tests/common/storage.rs
champ/node/tests/storage_test.rs
champ/node/validation/block.rs

Signed-off-by: Henry Gressmann <mail@henrygressmann.de>

feat: integrate proto/adad changes

---

Cargo.lock
champ/lib/crypto/lib.rs
champ/node/p2p/server.rs

feat: adds pong response (TG-33)

---

Cargo.lock
champ/node/blockpool/pool.rs
champ/node/consensus/voting_power.rs
champ/node/p2p/server.rs

feat: started logic for processing final votes (TG-33)
